repos:
  - repo: local
    hooks:
      - id: ament_clang_format
        name: ament_clang_format
        description: Code style checking using clang-format.
        language: system
        types: [c++]
        entry: ament_clang_format --config .clang-format --reformat
      - id: isort
        name: isort
        description: Sort Python imports.
        language: system
        types: [python]
        entry: isort --profile black --force-sort-within-sections
      - id: black
        name: black
        description: Format Python code.
        language: system
        types: [python]
        entry: black
      - id: ament_lint_cmake
        name: ament_lint_cmake
        description: Check CMake code style using cmakelint.
        language: system
        types: [cmake]
        entry: ament_lint_cmake
      - id: ament_pep257
        name: ament_pep257
        description: Check Python code style using pep257.
        language: system
        types: [python]
        entry: ament_pep257
      - id: xmllint_format
        name: xmllint_format
        description: Format XML files using xmllint.
        language: system
        types: [xml]
        entry: bash -c 'for f in "$@"; do xmllint --format --output "$f" "$f"; done' --
      - id: ament_xmllint
        name: ament_xmllint
        description: Check XML markup using xmllint.
        language: system
        types: [xml]
        entry: ament_xmllint
